name: Prettier
on:
  pull_request:
    branches:
      - alpha
  workflow_dispatch:
jobs:
  prettier:
    name: Prettify code
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # https://github.com/actions/checkout/issues/455#issuecomment-792228083
          ref: ${{ github.event_name == 'workflow_dispatch' && github.ref || github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install npm dependencies
        run: npm install

      - name: Run Prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write .
          commit_message: 'style(prettier): run prettier'
          prettier_plugins: 'prettier-plugin-svelte prettier-plugin-tailwindcss'
